FROM        ubuntu:20.10

RUN         apt-get update && apt-get install -y build-essential gnupg python3 python3-setuptools python3-pip
WORKDIR     /app
ADD        . /app/
RUN         pip3 install -r requirements.txt

CMD        [ "uwsgi", "app.ini" ] 