version: '3.7'

services:

  flask:
    build: 
      context: .
      dockerfile: Dockerfile-app
    container_name: Flask  
    volumes:
      - "./:/app"
    expose:
      - 8080
    environment:
      - DATABASE_URL=sqlite:///urls.db
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: Nginx
    restart: always  
    ports:
      - "80:80"
  